"""drop teacher specialization column

Revision ID: 31c72c202ed6
Revises: ea967deafaa8
Create Date: 2026-08-14 20:18:06.134121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31c72c202ed6'
down_revision: Union[str, Sequence[str], None] = 'ea967deafaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
