"""add student financial hold exemption

Revision ID: 3bc2c11813be
Revises: 8413db462bc2
Create Date: 2026-10-06 16:59:35.554179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bc2c11813be'
down_revision: Union[str, Sequence[str], None] = '8413db462bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_hold_exempt', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('financial_hold_notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('financial_hold_notes')
        batch_op.drop_column('financial_hold_exempt')

    # ### end Alembic commands ###
