"""add audit log, student address/status/created_at

Revision ID: 66c098226d21
Revises: ac07d015a9f6
Create Date: 2026-08-14 12:19:28.830866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66c098226d21'
down_revision: Union[str, Sequence[str], None] = 'ac07d015a9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_created_at'), ['created_at'], unique=False)

    # PostgreSQL: النوع المعدَّد يجب أن يُنشأ صراحةً قبل إضافة عمود يستخدمه (SQLite: لا يفعل شيئًا)
    sa.Enum('ACTIVE', 'LISTENER', 'SUSPENDED', 'TRANSFERRED', name='studentstatus').create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'LISTENER', 'SUSPENDED', 'TRANSFERRED', name='studentstatus'), nullable=False, server_default='ACTIVE'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('address')

    sa.Enum(name='studentstatus').drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_created_at'))

    op.drop_table('auditlog')
    # ### end Alembic commands ###
