"""add financial system

Revision ID: 8413db462bc2
Revises: cab971624f24
Create Date: 2026-10-06 16:42:36.541037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8413db462bc2'
down_revision: Union[str, Sequence[str], None] = 'cab971624f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# السندات وتوزيعاتها ثابتة: أي UPDATE/DELETE مرفوض على مستوى قاعدة البيانات نفسها
# (طبقة ثالثة بعد حدث الـ ORM وغياب مسارات التعديل في الـ API). التصحيح بسند عكس فقط.
_IMMUTABLE_TABLES = ("payment_receipts", "receipt_allocations")
_MESSAGE = "financial records are immutable: use a reversal receipt"


def _create_immutability_guards() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(
            f"CREATE FUNCTION forbid_financial_change() RETURNS trigger AS $$ "
            f"BEGIN RAISE EXCEPTION '{_MESSAGE}'; END; $$ LANGUAGE plpgsql"
        )
    for table in _IMMUTABLE_TABLES:
        for action in ("UPDATE", "DELETE"):
            name = f"trg_{table}_no_{action.lower()}"
            if dialect == "sqlite":
                op.execute(
                    f"CREATE TRIGGER {name} BEFORE {action} ON {table} "
                    f"BEGIN SELECT RAISE(ABORT, '{_MESSAGE}'); END"
                )
            elif dialect == "postgresql":
                op.execute(
                    f"CREATE TRIGGER {name} BEFORE {action} ON {table} "
                    f"FOR EACH ROW EXECUTE FUNCTION forbid_financial_change()"
                )


def _drop_immutability_guards() -> None:
    dialect = op.get_bind().dialect.name
    for table in _IMMUTABLE_TABLES:
        for action in ("update", "delete"):
            name = f"trg_{table}_no_{action}"
            if dialect == "sqlite":
                op.execute(f"DROP TRIGGER IF EXISTS {name}")
            elif dialect == "postgresql":
                op.execute(f"DROP TRIGGER IF EXISTS {name} ON {table}")
    if dialect == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS forbid_financial_change()")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('fee_structures',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('grade_level', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('term', sa.Enum('FIRST', 'SECOND', name='term'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('max_discount_percent >= 0 AND max_discount_percent <= 100', name='ck_fee_structure_discount_range'),
    sa.CheckConstraint('total_amount > 0', name='ck_fee_structure_total_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_level', 'academic_year', 'name', name='uq_fee_structure_identity')
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_grade_level'), ['grade_level'], unique=False)

    op.create_table('student_fees',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Uuid(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('amount_due >= 0', name='ck_student_fee_due_non_negative'),
    sa.CheckConstraint('discount_amount >= 0 AND discount_amount <= amount_due', name='ck_student_fee_discount_range'),
    sa.CheckConstraint('net_amount = amount_due - discount_amount', name='ck_student_fee_net_consistent'),
    sa.CheckConstraint('paid_amount >= 0 AND paid_amount <= net_amount', name='ck_student_fee_paid_range'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'fee_structure_id', name='uq_student_fee_assignment')
    )
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_fees_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_fee_structure_id'), ['fee_structure_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_student_id'), ['student_id'], unique=False)

    op.create_table('payment_plans',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_fee_id', sa.Uuid(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_plan_amount_positive'),
    sa.CheckConstraint('installment_no > 0', name='ck_plan_number_positive'),
    sa.CheckConstraint('paid_amount >= 0 AND paid_amount <= amount', name='ck_plan_paid_range'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_fee_id', 'installment_no', name='uq_plan_installment_no')
    )
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plans_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_student_fee_id'), ['student_fee_id'], unique=False)

    op.create_table('payment_receipts',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('kind', sa.Enum('PAYMENT', 'REVERSAL', name='receiptkind'), nullable=False),
    sa.Column('student_fee_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'TRANSFER', 'ZAIN_CASH', name='paymentmethod'), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reversal_of_id', sa.Uuid(), nullable=True),
    sa.Column('reversal_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_receipt_amount_positive'),
    sa.CheckConstraint('reversal_of_id IS NULL OR reversal_reason IS NOT NULL', name='ck_receipt_reversal_has_reason'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['payment_receipts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_receipt_idempotency_key'),
    sa.UniqueConstraint('receipt_number', name='uq_receipt_number'),
    sa.UniqueConstraint('reversal_of_id', name='uq_receipt_single_reversal')
    )
    with op.batch_alter_table('payment_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_receipts_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_receipt_number'), ['receipt_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_student_fee_id'), ['student_fee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_student_id'), ['student_id'], unique=False)

    op.create_table('receipt_allocations',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('installment_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_allocation_amount_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['installment_id'], ['payment_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['payment_receipts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id', 'installment_id', name='uq_allocation_receipt_installment')
    )
    with op.batch_alter_table('receipt_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_allocations_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_allocations_installment_id'), ['installment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipt_allocations_receipt_id'), ['receipt_id'], unique=False)

    # ### end Alembic commands ###
    _create_immutability_guards()


def downgrade() -> None:
    """Downgrade schema."""
    _drop_immutability_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_allocations_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_allocations_installment_id'))
        batch_op.drop_index(batch_op.f('ix_receipt_allocations_created_by'))

    op.drop_table('receipt_allocations')
    with op.batch_alter_table('payment_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_receipts_student_id'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_student_fee_id'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_created_by'))

    op.drop_table('payment_receipts')
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plans_student_fee_id'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_due_date'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_created_by'))

    op.drop_table('payment_plans')
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_fees_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_fees_fee_structure_id'))
        batch_op.drop_index(batch_op.f('ix_student_fees_created_by'))

    op.drop_table('student_fees')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structures_grade_level'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_created_by'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_academic_year'))

    op.drop_table('fee_structures')
    op.drop_table('receipt_counters')
    # ### end Alembic commands ###
