"""add teacher attendance

Revision ID: 88ea753d6bbb
Revises: febbca6ff694
Create Date: 2026-08-14 22:30:10.599299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88ea753d6bbb'
down_revision: Union[str, Sequence[str], None] = 'febbca6ff694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacherattendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', name='teacherattendancestatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'attendance_date')
    )
    with op.batch_alter_table('teacherattendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacherattendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacherattendance_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacherattendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacherattendance_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacherattendance_attendance_date'))

    op.drop_table('teacherattendance')
    # ### end Alembic commands ###
