"""add teacher status enum

Revision ID: 8ba70a73a4a8
Revises: 66c098226d21
Create Date: 2026-08-14 13:05:10.370903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ba70a73a4a8'
down_revision: Union[str, Sequence[str], None] = '66c098226d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL: إنشاء النوع المعدَّد صراحةً قبل استخدامه في عمود جديد
    sa.Enum('ACTIVE', 'ON_LEAVE', 'INACTIVE', name='teacherstatus').create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'INACTIVE', name='teacherstatus'), nullable=False, server_default='ACTIVE'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
