"""add roles, permissions, attendance

Revision ID: ac07d015a9f6
Revises: 2342724855b4
Create Date: 2026-08-14 09:35:38.504240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac07d015a9f6'
down_revision: Union[str, Sequence[str], None] = '2342724855b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'LEFT_EARLY', name='attendancestatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'attendance_date')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_student_guardian_user_id', 'user', ['guardian_user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        if op.get_bind().dialect.name != 'postgresql':
            batch_op.alter_column('role',
                   existing_type=sa.VARCHAR(length=7),
                   type_=sa.Enum('ADMIN', 'TEACHER', 'ACCOUNTANT', 'PARENT', name='userrole'),
                   existing_nullable=False)
        batch_op.create_foreign_key('fk_user_teacher_id', 'teacher', ['teacher_id'], ['id'])

    if op.get_bind().dialect.name == 'postgresql':
        # النوع userrole أُنشئ في أول migration بقيم ADMIN/TEACHER/STAFF؛ نستبدله بالقيم الجديدة (STAFF ⇒ ACCOUNTANT)
        op.execute("ALTER TYPE userrole RENAME TO userrole_old")
        sa.Enum('ADMIN', 'TEACHER', 'ACCOUNTANT', 'PARENT', name='userrole').create(op.get_bind())
        op.execute(
            "ALTER TABLE \"user\" ALTER COLUMN role TYPE userrole USING "
            "(CASE role::text WHEN 'STAFF' THEN 'ACCOUNTANT' ELSE role::text END)::userrole"
        )
        op.execute("DROP TYPE userrole_old")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_teacher_id', type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'TEACHER', 'ACCOUNTANT', 'PARENT', name='userrole'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('can_manage_users')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_guardian_user_id', type_='foreignkey')
        batch_op.drop_column('guardian_user_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
