"""add subjects and timetable

Revision ID: c1e5e2ad03b7
Revises: 8ba70a73a4a8
Create Date: 2026-08-14 13:15:40.715266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1e5e2ad03b7'
down_revision: Union[str, Sequence[str], None] = '8ba70a73a4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_name'), ['name'], unique=True)

    op.create_table('timetableslot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', name='weekday'), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'day', 'period_number')
    )
    with op.batch_alter_table('timetableslot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetableslot_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetableslot_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetableslot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timetableslot_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_timetableslot_classroom_id'))

    op.drop_table('timetableslot')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_name'))

    op.drop_table('subject')
    # ### end Alembic commands ###
