"""add exams grades and report cards

Revision ID: cab971624f24
Revises: 88ea753d6bbb
Create Date: 2026-10-06 16:08:17.606447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cab971624f24'
down_revision: Union[str, Sequence[str], None] = '88ea753d6bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('exam_type', sa.Enum('QUIZ', 'ASSIGNMENT', 'ORAL', 'PRACTICAL', 'MIDTERM', 'FINAL', name='examtype'), nullable=False),
    sa.Column('term', sa.Enum('FIRST', 'SECOND', name='term'), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'LOCKED', name='examstatus'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_score > 0 AND max_score <= 1000', name='ck_exam_max_score_range'),
    sa.CheckConstraint('weight_percent > 0 AND weight_percent <= 100', name='ck_exam_weight_range'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'subject_id', 'term', 'academic_year', 'title', name='uq_exam_identity')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_term'), ['term'], unique=False)

    op.create_table('exam_results',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('GRADED', 'ABSENT', 'EXCUSED', name='resultstatus'), nullable=False),
    sa.Column('teacher_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('internal_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='ck_result_score_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_result_exam_student')
    )
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_results_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_results_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_results_student_id'), ['student_id'], unique=False)

    op.create_table('report_cards',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Enum('FIRST', 'SECOND', name='term'), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('overall_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_result', sa.Enum('PASSED', 'FAILED', 'INCOMPLETE', name='overallresult'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='reportcardstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('overall_percentage IS NULL OR (overall_percentage >= 0 AND overall_percentage <= 100)', name='ck_reportcard_percentage_range'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term', 'academic_year', name='uq_reportcard_student_term')
    )
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_cards_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_cards_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_cards_student_id'), ['student_id'], unique=False)

    op.create_table('report_card_entries',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_card_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('weighted_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('weighted_percentage >= 0 AND weighted_percentage <= 100', name='ck_entry_percentage_range'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['report_card_id'], ['report_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_card_id', 'subject_id', name='uq_entry_card_subject')
    )
    with op.batch_alter_table('report_card_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_card_entries_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_card_entries_report_card_id'), ['report_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_card_entries_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_card_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_card_entries_subject_id'))
        batch_op.drop_index(batch_op.f('ix_report_card_entries_report_card_id'))
        batch_op.drop_index(batch_op.f('ix_report_card_entries_created_by'))

    op.drop_table('report_card_entries')
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_cards_student_id'))
        batch_op.drop_index(batch_op.f('ix_report_cards_status'))
        batch_op.drop_index(batch_op.f('ix_report_cards_created_by'))

    op.drop_table('report_cards')
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_results_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_exam_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_created_by'))

    op.drop_table('exam_results')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_term'))
        batch_op.drop_index(batch_op.f('ix_exams_subject_id'))
        batch_op.drop_index(batch_op.f('ix_exams_status'))
        batch_op.drop_index(batch_op.f('ix_exams_created_by'))
        batch_op.drop_index(batch_op.f('ix_exams_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_exams_academic_year'))

    op.drop_table('exams')
    # ### end Alembic commands ###
