"""add curriculum requirements and teacher subjects

Revision ID: ea967deafaa8
Revises: c1e5e2ad03b7
Create Date: 2026-08-14 13:59:44.451198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea967deafaa8'
down_revision: Union[str, Sequence[str], None] = 'c1e5e2ad03b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculumrequirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_level', 'subject_id', name='uq_curriculum_grade_subject')
    )
    with op.batch_alter_table('curriculumrequirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculumrequirement_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculumrequirement_subject_id'), ['subject_id'], unique=False)

    op.create_table('teachersubject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', name='uq_teacher_subject')
    )
    with op.batch_alter_table('teachersubject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachersubject_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachersubject_teacher_id'), ['teacher_id'], unique=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_periods_per_week', sa.Integer(), nullable=False, server_default='24'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('max_periods_per_week')

    with op.batch_alter_table('teachersubject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachersubject_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teachersubject_subject_id'))

    op.drop_table('teachersubject')
    with op.batch_alter_table('curriculumrequirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculumrequirement_subject_id'))
        batch_op.drop_index(batch_op.f('ix_curriculumrequirement_grade_level'))

    op.drop_table('curriculumrequirement')
    # ### end Alembic commands ###
