"""add teacher grade scope

Revision ID: febbca6ff694
Revises: 31c72c202ed6
Create Date: 2026-08-14 20:53:26.613932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'febbca6ff694'
down_revision: Union[str, Sequence[str], None] = '31c72c202ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachergrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('grade_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'grade_level', name='uq_teacher_grade')
    )
    with op.batch_alter_table('teachergrade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachergrade_grade_level'), ['grade_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachergrade_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachergrade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachergrade_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teachergrade_grade_level'))

    op.drop_table('teachergrade')
    # ### end Alembic commands ###
